### ISSUE TITLE
   [feature request] - Open Terminal at the Current Maven Module Path - Option for Git Bash?

### ISSUE THREAD

**Issue by JWT007** [krasa/MavenHelper#100]
Just installed the plugin and I love the idea of the right-click menu option to open a terminal at the given path, 

However it would be nice if there was a configuration option for whether to open the windows powershell or the git bash shell - since I usually avoid powershell like the plague :).

**Comment by krasa** [comment]
Have you tried `File | Settings | Tools | Terminal`?

**Comment by JWT007** [comment]
d'oh no I didn't realize you could set the default there... sorry and thank you :) closing this - appreciate the help!
