### ISSUE TITLE
Feature request: combine dependencies in the maven tool view with this plugin

### ISSUE THREAD

**Issue by umjammer** [krasa/MavenHelper#107]
i like this plugin!

one more thing,
dependencies in the "Maven Tool View" (right side) should combine jars in the left pane in "Dependency Analyzer".

thanks!

<img width="572" alt="スクリーンショット 2023-09-14 5 51 18" src="https://github.com/krasa/MavenHelper/assets/493908/cc636d0a-5dae-4f4e-bc72-5ab4ae1f439e">

**Comment by krasa** [comment]
i do not understand

**Comment by umjammer** [comment]
i mean
when i click one of dependency in the "maven tool view" (red circle above)
this plugin's cursor (at the left plugin pane) should move to the same jar.

does it make sense?

**Comment by krasa** [comment]
Yes. But "maven tool view" is made by Jetbrains, I do not think it is possible.

**Comment by umjammer** [comment]
my bad, not "maven tool view" but "Structure tool view".
"Structure tool view" is blank when "Dependency Analyzer" is active.
there may be plugin api to send data to the structure view, isn't it?

**Comment by krasa** [comment]
yes, but what for?

**Comment by umjammer** [comment]
because it's faster than filtering

**Comment by krasa** [comment]
Do you mean that you want this speed search?
![image](https://github.com/krasa/MavenHelper/assets/1160875/2186de69-6492-4d26-873f-1d426c27cd4c)

**Comment by umjammer** [comment]
no, like your previous post is possible by this plugin's search box.

this is my pom.xml
<img width="300" alt="ss 2023-09-16 6 37 19" 
src="https://github.com/krasa/MavenHelper/assets/493908/bef1831d-57d1-40f0-92e5-69d2e1822783">

and this is the structure view of the pon.xml when "Text" tab is active.
<img width="200" alt="ss 2023-09-16 6 38 36" src="https://github.com/krasa/MavenHelper/assets/493908/99c1467a-0bb9-424f-9f3b-9a2e6b8cdcf2">

this case there are so many dependency jars in the plugin pane that the pane shows a scroll bar,
on the other hand jars in structure pane that i wrote is fewer than the former.
so that it's easier to find a target jar in the structure view.

**Comment by krasa** [comment]
so collapse the tree?
![Uploading image.png…]()

**Comment by umjammer** [comment]
oh i didn't know that way.

i got convinced.
