### ISSUE TITLE
Conflicting relationships between different language versions of the same package name are not recognized.

### ISSUE THREAD

**Issue by Tiakon** [krasa/MavenHelper#108]
**Describe the bug**

A dependency compiled in different language versions of the same package name cannot be identified as a conflicting dependency.

**To Reproduce**

The project dependency structure is as follows:

project1
- project2
- json4s-scalap_2.13:3.6.6

project2
-  json4s-scalap_2.11:3.7.0-M11

![image](https://github.com/krasa/MavenHelper/assets/21116907/40e9e8a9-eb4b-4f9c-82ac-848cd4d8f1ae)

**Expected behavior**
In this case, I understand that  json4s-scalap_2.13:3.6.6 and  json4s-scalap_2.11:3.7.0-M11 should be identified as conflicting dependencies, but this is not the case.

**Comment by krasa** [comment]
but in the end, you still see that `scala-library` is conflicting and all those libraries in the right column, yes?

**Comment by Tiakon** [comment]
Yes.
