### ISSUE TITLE
How to resolve Maven dependencies into a tree structure?

### ISSUE THREAD

**Issue by a1156698162** [krasa/MavenHelper#109]
Hello, I have a question about how Maven Helper parses Pom dependencies into a tree structure. I have looked at the code implementation and did not find how this step is done. Could you please explain how this parsing process is done? Thank you! @krasa

**Comment by krasa** [comment]
It does not, it is done by IntelliJ using some Maven API like `org.eclipse.aether.impl.ArtifactResolver`.

**Comment by a1156698162** [comment]
Okay, I understand. Thank you very much for your patient response. I have another question. I also want to parse the pom file into a tree structure using the org.jetbrains.idea.maven.project.MavenProject#getDependencyTree method. However, I haven't figured out how these dependencies are imported into the project. I am using Maven to manage dependencies, but I am not sure which Maven coordinates I need to import. @krasa

**Comment by krasa** [comment]
What is your use case? Are you making an IntelliJ plugin?

**Comment by a1156698162** [comment]
No. I want to create a functionality similar to Maven Helper, but it is not an IntelliJ plugin. I want to analyze the dependency relationship based on the content of the pom file and store it, making it easy to query and display on a webpage.

**Comment by krasa** [comment]
Then you cannot use `org.jetbrains.idea.maven.project.MavenProject#getDependencyTree`.

https://stackoverflow.com/a/40820480/685796

**Comment by a1156698162** [comment]
Okay, I got it. Thank you very much, thank you!
