### ISSUE TITLE
Unable to modify settings in IntelliJ 2016.1

### ISSUE THREAD

**Issue by jdeketelaere** [krasa/MavenHelper#12]
After migrating to IntelliJ 2016.1 (Ultimate edition) - although plugin functionality is still present, the settings can no longer be modified since the entry for Maven Helper is missing under Preferences > Other Settings.

Kind Regards,
J

**Comment by duponter** [comment]
Found a possible solution in a similar issue for another plugin: 
https://github.com/kstenschke/shifter-plugin/issues/24

> https://youtrack.jetbrains.com/issue/IDEA-150516
> you need to split ProjectComponent and Configurable into separate classes and use

```
<extensions defaultExtensionNs="com.intellij">
    <projectConfigurable ... />
</extensions>
```

**Comment by krasa** [comment]
fixed
