### ISSUE TITLE
Opened Dependency Analyzer UI immediately switches to text again

### ISSUE THREAD

**Issue by w123wh** [krasa/MavenHelper#120]
There seems to be some problem with the plugin, opening the Dependency Analyzer in the pom file interface and not being able to view the plugin UI, neither IntelliJ IDEA 2024.2.2 (Ultimate Edition) nor IntelliJ IDEA 2024.1.2 (Ultimate Edition) works properly

**Comment by krasa** [comment]
works fine for me, screenshot pls. 
anything in the log?

**Comment by w123wh** [comment]
https://github.com/user-attachments/assets/0c50b1bd-e516-425d-a99c-1a8fec9db828

Whether the log path can be provided, no error is displayed in IDEA during use

**Comment by w123wh** [comment]
I found the reason why it didn't work, it was conflicting with other plugins, and was there a way to help troubleshoot？

**Comment by krasa** [comment]
If you would find the plugin that causes it, I could take a look.

**Comment by krasa** [comment]
Anyways, this is a broken core IDE function, nothing I can do about it in my plugin imho.

**Comment by w123wh** [comment]
I've identified the issue, thanks for your reply

**Comment by krasa** [comment]
Please share what it was.

**Comment by w123wh** [comment]
I used a niche plugin codeRevide with a snippet of code that forced it to switch to the editing interface causing the maven helper not to work
https://github.com/veezean/IntellijIDEA-CodeReview-Plugin

**Comment by krasa** [comment]
Thanks! Do you want any more help?

**Comment by apacheBright** [comment]
May I ask when the defect is scheduled to be fixed？

**Comment by krasa** [comment]
Don't ask me. I cannot fix it.

**Comment by sunxiang0918** [comment]
> I used a niche plugin codeRevide with a snippet of code that forced it to switch to the editing interface causing the maven helper not to work https://github.com/veezean/IntellijIDEA-CodeReview-Plugin

Thank you for explaining the reason. I have been confused for a long time. I always thought it was a problem with the 'maven helper'. After checking, I also installed this plug-in... Just disable it. `MavenHelper` worked fine! .. But the strange thing is that it was before the 2024.1 version. It's all right...
