### ISSUE TITLE
Your settings indicates, that conflicts will not be visible

### ISSUE THREAD

**Issue by natros** [krasa/MavenHelper#14]
From my understanding, the IDEA-133,331 problem is solved, however I get the following warning:

> If your project is Maven2 compatible, you could try one of the following:
> * press Apply Fix button to alter Maven VM options for importer (might cause trouble for IJ 2016.1+)
> * turn off File | Settings | Build, Execution, Deployment | Build Tools | Maven | Importing | Use Maven3 to import project setting
> * use IJ 2016.1+ and configure it to use external Maven 3.3.1+ (File | Settings | Build, Execution, Deployment | Build Tools | Maven | Maven home directory)
> 

I'm using IJ 2016.1.2 with maven 3.3.9 In this case the warning should not be seen.

IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_92-b14 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by krasa** [comment]
thanks, I forgot to check maven version.
fixed.

**Comment by natros** [comment]
you were amazingly fast fixing the issue

thank you.
