### ISSUE TITLE
All Dependencies view shows only parent's dependencies

### ISSUE THREAD

**Issue by tttomat19** [krasa/MavenHelper#15]
https://gist.github.com/tttomat19/618edcf36cc137a6ed6029aefd82658d
you may find in gist
1. actual dependency tree
2. parent pom
3. project's pom

structure is the following
spring-boot-starter-parent is parent of shd3-parent; and shd3-parent is parent of shd3-importer (end project)

on screenshot there are only dependencies of shd3-parent for shd3-importer.

![image](https://cloud.githubusercontent.com/assets/6590011/17661432/ce79b0fc-62e7-11e6-935d-383a9ba2d3c0.png)

Might be something tricky about spring-boot-starter-parent and absent explicit versions in poms.
I'll try to make MRE later.

**Comment by krasa** [comment]
related? https://youtrack.jetbrains.com/issue/IDEA-133331#comment=27-1323737

**Comment by Aloren** [comment]
Hi. I can confirm that I have the same issue.
@krasa So the issue is actually with Intellij Idea? There is no workaround for it in plugin? 
Thanks!

**Comment by krasa** [comment]
@Aloren Do you have `-Didea.maven3.use.compat.resolver` in  File | Settings | Build, Execution, Deployment | Build Tools | Maven | Importing | VM options ....? If so, then remove it.

**Comment by krasa** [comment]
And yes, the bug is in IntelliJ itself, the workaround is to have a new IntelliJ with a bundled Maven 3.1.1+  - so it does not need `-Didea.maven3.use.compat.resolver`.

**Comment by Aloren** [comment]
Great! Thank you!
