### ISSUE TITLE
Dependency Analyzer changes based on packaging type

### ISSUE THREAD

**Issue by zkendall** [krasa/MavenHelper#17]
I have a pom that has
```<packaging>war</packaging>```
and the Dependency Analyzer tab only shows a fraction of the actual dependencies. But if I comment out this line all the dependencies show.

Let me know how I can provide more information to help resolve this.

**Comment by krasa** [comment]
Dependencies are provided by IntelliJ, if not even Maven Diagram has them, then it is a bug for Jetbrains.
![image](https://user-images.githubusercontent.com/1160875/27096967-08d73a34-5073-11e7-9ba0-9fe7bf8056f6.png)
