### ISSUE TITLE
Dependency analyzer shows wrong version for "compile"

### ISSUE THREAD

**Issue by diskostu** [krasa/MavenHelper#18]
The Maven docs say that for so called _transitive dependencies_, there are some rules that make clear which dependency version wins.

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

1. The shortest path wins. Quote from the docs:
> if dependencies for A, B, and C are defined as A -> B -> C -> D 2.0 and A -> E -> D 1.0, then D 1.0 will be used when building A because the path from A to D through E is shorter

2. Next rule if two dependencies are at the same level. Quote from the docs:
> If two dependency versions are at the same depth in the dependency tree, [...] it's the order in the declaration that counts: the first declaration wins.

The Plugin _MavenHelper_ does not respect these rules, especially not the second one. I think MavenHelper takes the **highest** version for granted, but that's just a guess.

**Comment by krasa** [comment]
Yeah, that's right. It was done to just highlight which dependencies you do not want, which are generally those with an older version.

**Comment by krasa** [comment]
Fixed by https://github.com/krasa/MavenHelper/pull/19
