### ISSUE TITLE
 not detecting conflicts in IDEA 14

### ISSUE THREAD

**Issue by natros** [krasa/MavenHelper#2]
I believe the plugin is not detecting conflicts with IDEA 14

**Comment by ddatsh** [comment]
what is the difference between maven2/3 import?

**Comment by krasa** [comment]
I have no idea

**Comment by igreenfield** [comment]
this fix '-Didea.maven3.use.compat.resolver' causing problems with intellij 2016.1 !

Do you have any fixes?

**Comment by krasa** [comment]
I can't do anything. But you can use external maven-3.3.9 without it.
