### ISSUE TITLE
[FEATURE REQUEST] Ability to configure custom maven goal for test

### ISSUE THREAD

**Issue by kenwang-okta** [krasa/MavenHelper#21]
It's great that we can configure custom goals, but those goals are run across the entire project.

Would it be possible to configure a goal that is run specifically for the selected class (i.e. append -Dtest/-Dit.test to the goal)?

Additionally, it would be awesome to be able to give these custom goals a custom name as well.

**Comment by krasa** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/1160875/29991158-d9c1a56e-8f82-11e7-987f-bb7ec24d88f5.png)

**Comment by krasa** [comment]
I think #32 kinda solves it...
![image](https://user-images.githubusercontent.com/1160875/58203758-2ca1e400-7cdb-11e9-902b-df04a4c2dee7.png)
