### ISSUE TITLE
Unable to run integration tests from IntelliJ

### ISSUE THREAD

**Issue by harishkannarao** [krasa/MavenHelper#3]
Hi,

Recently I tried this plugin in IntelliJ and I was very handly to run single test class or a single test case in a Test file.
However I am unable to run a test if the surefire plugin is configured to run in integration-test phase of Maven.

Steps to reproduce:
1) Create a Maven project and configure surefire plugin or failsafe plugin to run the test in integration-test phase instead of test phase.  Normally this is used for test modules containing integration tests
2) Create a test class in the test source folder
3) Open the file in IntelliJ
4) Right click in the editor and select "Run Maven -> Test SomeSampleIntegrationTest"

Expected result:
Maven build should run and execute the test class

Actual result:
Maven build successfully, however the test class is not run as the test is configured to run in integration-test phase of maven

Proposed solution:
When we right click in the editor, users can be given two options under "Run Maven":
1) Test SomeSampleIntegrationTest
2) Integration Test SomeSampleIntegrationTest

Selecting the second option, should execute till integration-test phase of maven.
In this way, if the surefire or failsafe plugin is configured to run the tests in integration-test phase, then the tests will be picked up.

Regards,
Harish

**Comment by krasa** [comment]
could you post me your config of surefire or failsafe plugin or make a quickstart?

**Comment by harishkannarao** [comment]
Hi Team,

Apologies for my delayed response.

I have created a sample github repo with three modules:
1) SurefireUnitTest
           com.harishkannarao.SurefireSampleUnitTest
2) SurefireIntegrationTest
           com.harishkannarao.SurefireSampleIntegrationTest
           com.harishkannarao.SurefireSampleIT
3) FailsafeIntegrationTest
           com.harishkannarao.FailsafeSampleIntegrationTest
           com.harishkannarao.FailsafeSampleIT

The plugin runs the following test, but doesn't run other tests:
com.harishkannarao.SurefireSampleUnitTest

Github repo: https://github.com/harishkannarao/MavenSurefireFailsafeExamples

**Comment by krasa** [comment]
Apologies for my delay. Not much time but I will definitely look into it soon.
Thanks.

**Comment by krasa** [comment]
Not even Netbeans can run those tests. 
I would suggest this way: 
https://github.com/harishkannarao/MavenSurefireFailsafeExamples/compare/master...krasa:master

**Comment by krasa** [comment]
What I could do is to check if m**aven-surefire-plugin** is configured with **skip=true**, if so then execute **integration-test** instead of **test-compile surefire:test**. Such dirty little hack might solve enough of cases.

**Comment by krasa** [comment]
Fixed. Thanks! 
Let me know if you need it in IJ 13 or older.
