### ISSUE TITLE
[IMPROVEMENT] Support ${revision} for <version>

### ISSUE THREAD

**Issue by danhaywood** [krasa/MavenHelper#33]
Maven 3.5.0 introduced the ability to externalize the <version> using the ${revision} placeholder (see https://maven.apache.org/maven-ci-friendly.html).

However, with maven-helper installed this results in an error in the editor, red squiggly under:

<version>${revision}</version>

**Comment by krasa** [comment]
Are you sure it is because of this plugin?

**Comment by krasa** [comment]
works fine for me
