### ISSUE TITLE
Can't work on idea 2018.3

### ISSUE THREAD

**Issue by eden214** [krasa/MavenHelper#37]
Can't work on idea 2018.3，show "Nothing to show"

**Comment by krasa** [comment]
works fine for me

**Comment by eden214** [comment]
@krasa I tried to restart my pc and re-install the plugin, but useless. All Dependencies as List still shows "Nothing to show"

here is my environment

IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018

JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by nortthon** [comment]
I'm having the same problem. 
I'm using The Ultimate Edition 2018.3 (Mac OS)

**Comment by lcardito** [comment]
@krasa is there anything we can provide/do for some investigation/debugging? I am experiencing the same issue on:

```
IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 26, 2018
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

Thanks!

**Comment by krasa** [comment]
do you have some open source project that can reproduce it?

do you have something special here?
![image](https://user-images.githubusercontent.com/1160875/49168466-d493b180-f337-11e8-86c9-674267185b43.png)

**Comment by eden214** [comment]
@krasa It seems nothing special.Except for one more line at the bottom
![qq 20181129104417](https://user-images.githubusercontent.com/13815955/49195937-ff2b4c00-f3c3-11e8-94ac-2bd296c4bbc7.png)

**Comment by lcardito** [comment]
My apologies it actually does work - I've realized I was pointing at a pom with only the `dependencyManagement` defined. So I suppose this works as expected for me. @eden214 I've literally uninstalled, restart and re-install the plugin.

Thanks again for the support!

**Comment by nortthon** [comment]
The "Dependency Analyzer" feature isn't working now here. About 2018.3 IntelliJ version.

**Comment by eden214** [comment]
@lcardito The plugin works before I update idea

**Comment by eden214** [comment]
I found it suddenly working again.But I did nothing...

**Comment by jerryqiang** [comment]
maybe you see a parent pom, there are only dependencies of **dependencyManagement**

**Comment by chauncychtt** [comment]
> I found it suddenly working again.But I did nothing...

me too, did you solve this problem?

**Comment by krasa** [comment]
@chauncychtt you are on 2018.3?

**Comment by nagarsogesn** [comment]
> My apologies it actually does work - I've realized I was pointing at a pom with only the `dependencyManagement` defined. So I suppose this works as expected for me. [@eden214](https://github.com/eden214) I've literally uninstalled, restart and re-install the plugin.
> 
> Thanks again for the support!

Thanks Man for saving a lot of time.
