### ISSUE TITLE
new goal is not editable

### ISSUE THREAD

**Issue by javamonkey79** [krasa/MavenHelper#39]
Problem:
When I click on: 
Run Maven -> New Goal

The combo dialog box is not fully editable. I can paste into it. I can backspace in it. I can select items already populated in it. I cannot type in it directly.

Intellij details:

IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Plugin details:
v3.7.172.1454.3

**Comment by krasa** [comment]
Cannot reproduce. 
It is a default IntelliJ dialog, so either IntelliJ or JRE has a bug.

**Comment by krasa** [comment]
I reimplemented the whole thing.
