### ISSUE TITLE
Change surefire parameters during Debug

### ISSUE THREAD

**Issue by Narimm** [krasa/MavenHelper#4]
Currently you are using -DForkmode=never to disable forking for debugging during surefire execution
however this is deprecated and values set in the pom will override it.
if 
```xml
                    <forkCount>1</forkCount>
                    <reuseForks>always</reuseForks>
```
 is set via the POM 

forkMode is ignored and surefire will fork test making the debugger miss them

you should also set 
-DforkCount=0 and -DreuseForks=always to avoid this.

**Comment by krasa** [comment]
fixed, thanks!
