### ISSUE TITLE
dependency exclusion seem not being considered

### ISSUE THREAD

**Issue by robs-nice99** [krasa/MavenHelper#43]
In the dependencies view ("Dependency Analyzer" botom tab after opening a pom.xml file) 

I was trying to exclude some transitive dependencies.
I wrote the name (lang3) in the text box.

Then all the dependencies, which had transitive dependencies matching "lang3" appeared. However, some of them were already excluded.

When I right click and pressed "exclude" I found the following duplicates:

```
            <exclusions>
                <exclusion>
                    <artifactId>org.apache.commons</artifactId>
                    <groupId>commons-lang3</groupId>
                </exclusion>
                <exclusion>
                    <groupId>commons-lang3</groupId>
                    <artifactId>org.apache.commons</artifactId>
                </exclusion>
            </exclusions>
```

Besides ordering the group before the artifact, it seems it didn't detect the previous exclusion.
Is this expected behavior?

**Comment by krasa** [comment]
Did you click reimport?

**Comment by robs-nice99** [comment]
I didn't. When should I do that?

**Comment by krasa** [comment]
When you make a change in poms and want IntelliJ to see it, or just enable `Import Maven projects automatically`.

**Comment by robs-nice99** [comment]
There was no change, except for the exclusion added (duplicated) with MavenHelper. Does it work correctly for you?

**Comment by krasa** [comment]
Works fine for me. Try to run `mvn dependency:tree -Dverbose`
