### ISSUE TITLE
Why do independencies still exist in the project after i excluded it?

### ISSUE THREAD

**Issue by fgy4010** [krasa/MavenHelper#47]
As the issue showing, i have no idea about this phnomenna. I wonder if there's a misopration or the bug in maven helper.I just do the steps as it describes on the tutorials: click Dependency Analyzer then right click on the red one and click the exclude. But it seems to not work and it shows up again in the Denpency Analayer in red color.

Could you help me out this question? Thx a lot.

**Comment by krasa** [comment]
The data are loaded from IntelliJ, and they are cached. You need to click on Reimport button.

**Comment by fgy4010** [comment]
It's so helpful! And thanks a lot for the advices! So good plugin i ever used. Thx!
