### ISSUE TITLE
2019.2、2019.3 idea compatibility

### ISSUE THREAD

**Issue by laocu** [krasa/MavenHelper#48]
It is found that the detection of some projects on the 2019.2 and 2019.3 versions of ideas will have no results, and the detection of the same project on earlier versions of ideas will have results.
Does the plugin have compatibility issues?

![image](https://user-images.githubusercontent.com/19768250/71609040-64053700-2bc0-11ea-92a4-a589f5d246df.png)
![image](https://user-images.githubusercontent.com/19768250/71609076-96169900-2bc0-11ea-9632-a906cf560989.png)
![image](https://user-images.githubusercontent.com/19768250/71609118-f1488b80-2bc0-11ea-9d7e-f3db4c17ae9a.png)

**Comment by krasa** [comment]
Try build-in GUI dependency graph, it will probably work the same, then report that to JetBrains. Something similar already happened https://youtrack.jetbrains.com/issue/IDEA-133331
