### ISSUE TITLE
Debug action passing -DforkMode=never makes tests fail

### ISSUE THREAD

**Issue by mattiasgronlund** [krasa/MavenHelper#57]
Thanks for a very useful plugin.

I did run into problem when using it together with com.google.testing.compile / compile-testing maven module, version 0.18.
Maven Helper is version 4.9.193.000.0

My problem is that when running the Maven Debug - test action, the following is logged in the console:
```
[WARNING] The parameter forkMode is deprecated since version 2.14. Use forkCount and reuseForks instead.
[WARNING] useSystemClassloader setting has no effect when not forking
```
And then the tests fails with:
```
java.lang.NoClassDefFoundError: org/apache/maven/plugin/AbstractMojo
	at testpackage.TestGeneratedCode.compileTestCases(TestGeneratedCode.java:73)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugin.AbstractMojo
	at testpackage..TestGeneratedCode.compileTestCases(TestGeneratedCode.java:73)
```

The problem is that even if I user maven surefire plugin 3.0.0-M4, Maven Helper still add the `-DforkMode=never` parameter when executing tests.

If I run `mvn test -DforkMode=never -DforkCount=0 -DreuseForks=false` or `mvn test -DforkMode=never` I get the same error on command line.

But if I instead use `mvn test -DforkCount=0 -DreuseForks=false` the tests are able to compile the generated sources and pass as expected.

**Comment by krasa** [comment]
Interesting, I expected it would get ignored, not break something.

**Comment by mattiasgronlund** [comment]
Thanks!
