### ISSUE TITLE
Disparate JDK versions causing Maven compile exceptions

### ISSUE THREAD

**Issue by Protonull** [krasa/MavenHelper#70]
Attempting to use Maven Helper to `compile` causes an exception and a failed build seemingly due to how Maven Helper inherits the SDK of the project. The project is written in and targets Java 11 since it's the LTS version, but Maven 3.8.1 uses Java 15 to run. So typing `mvn compile` in a terminal works fine, but when using Maven Helper, since it inherits the JDK from the project SDK, means that Maven is being run with Java 11 and thus causing exceptions with plugins written for newer versions of Maven.

**Comment by krasa** [comment]
Isn't that just how IntelliJ works? It uses Project SDK, or this:
![image](https://user-images.githubusercontent.com/1160875/119169148-f92cf800-ba61-11eb-846e-ce19b5ccb4c9.png)

**Comment by Protonull** [comment]
Huh, TIL, that fixed it. Would it be possible to add a link to that Runner page on Maven Helper's options page for anyone else who runs into this problem and isn't aware of this option buried several layers deep? :P
