### ISSUE TITLE
resolve/ignore extension provided properties

### ISSUE THREAD

**Issue by delanym** [krasa/MavenHelper#72]
I use this Maven [extension](https://github.com/pascalgn/properties-maven-extension) to set a property with the value of the git worktree directory, among others.
I also leave the a property `<git.dir.worktree>${git.dir.worktree}</git.dir.worktree>` in the top-level pom to fail the build if for some reason the extension doesn't run. But this completely breaks IDEA's ability to resolve packages.
https://github.com/pascalgn/properties-maven-extension/issues/59

What's the best approach here?

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issues/IDEA?q=%22Properties%20Maven%20Plugin%22

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-79152#focus=Comments-27-282246.0-0

**Comment by delanym** [comment]
@krasa i don't have the option of using a plugin over of an exception. I'm basically asking _when_ will IDEA support this?

**Comment by krasa** [comment]
I am not an IDEA developer :-)

I would suggest not using extensions that require IDE support.

**Comment by delanym** [comment]
The extension doesn't require IDE support - the IDE requires support for the extension, but I see your point about this being a mere plugin.

**Comment by krasa** [comment]
Funny, I had this problem 10 years ago too https://youtrack.jetbrains.com/issue/IDEA-75122

**Comment by delanym** [comment]
I need the extension to set git properties for the build as it does this once for the whole build. If I do that with a git-*-plugin it will query git 500x. Of course I could make that info inheritable, but that rules out using -pl type builds
