### ISSUE TITLE
[Feature Request]provide ability to find where is the version come from

### ISSUE THREAD

**Issue by shpodg** [krasa/MavenHelper#77]
every time i saw the version of the dependency , I want to know who determined the final version.

**Comment by krasa** [comment]
IntelliJ provides one property which perhaps identifies it, but not sure if it is always correct.

It seems to be both the first and the shortest dependency in the tree - I've added `*` there. Not sure if it is worth having this feature, as it complicates the GUI.
![image](https://user-images.githubusercontent.com/1160875/134474841-502add62-6c14-4000-b284-135f3aef256e.png)
![image](https://user-images.githubusercontent.com/1160875/134474866-d85eb959-b30a-4a4a-aca6-a87279470314.png)

**Comment by krasa** [comment]
you can try it: 
[MavenRunHelper.zip](https://github.com/krasa/MavenHelper/files/7215999/MavenRunHelper.zip)
