### ISSUE TITLE
Not working with dependencyManagement?

### ISSUE THREAD

**Issue by pravussum** [krasa/MavenHelper#8]
I have a rather large maven project with a parent pom containing a lot of dependencies inside a dependencyManagement-tag.
These dependencies are not shown in the Dependency analyzer tab (in fact, its completely empty).
Once I remove the surrounding dependencyManagement element, the dependencies are shown.

**Comment by krasa** [comment]
Seems ok to me, dependencyManagement does not put them on classpath, afaik. 
Not sure how Eclipse displays it...

**Comment by pravussum** [comment]
Yeah, actually makes sense. Closing.
