### ISSUE TITLE
The history icon ( magnifying glass ) in the search field handles mouse events incorrectly

### ISSUE THREAD

**Issue by PorkLip** [krasa/MavenHelper#86]
**Describe the bug**
The history icon ( magnifying glass ) in the search field handles mouse events incorrectly. 

**To Reproduce**
1. Enter a couple of different search texts in the search field to populate the history dropdown
2. Enter WWW in the search field
3. Click ( and hold ) the mouse button in the search field to the right of the last character in WWW
4. Move the cursor to the right over WWW and continue over the history icon ( magnifying glass )
5. When the mouse exits the history icon ( magnifying glass ) the history dropdown is shown even though the mouse button never was released over the icon.

**Expected behavior**
The history dropdown of the search field should only appear when the history icon ( magnifying glass ) is clicked ( mouse buttons is pressed and released on the icon, or it is at least released over the icon )

**Environment :**
Mac OS 12.1
IntelliJ 2021.3.1

**Comment by krasa** [comment]
history icon? 
screenshot pls

**Comment by krasa** [comment]
or even better a gif

**Comment by PorkLip** [comment]
https://user-images.githubusercontent.com/3833881/148428915-69013898-ac14-425a-9c21-d6236a52e2be.mov

**Comment by krasa** [comment]
That is an IntelliJ bug, Search fields at Settings behave the same.

**Comment by PorkLip** [comment]
Ok, will you report it or shall I?

**Comment by krasa** [comment]
you, thanks.

**Comment by PorkLip** [comment]
Seems to already have been reported: [Search History button incorrectly handles mouse-dragged-over event](https://youtrack.jetbrains.com/issue/IDEA-267197).
Added my vote to it at least.
