### ISSUE TITLE
Would it be possible to add "Profile ... " to the Run and Debug context menu actions?

### ISSUE THREAD

**Issue by kingsfleet** [krasa/MavenHelper#87]
**Describe the bug**
You cannot quickly profile a maven job, in this case to work out why a test was failing a performance metric only when run using Maven.

**To Reproduce**
Right click on an Java Test method, there is no Profile maven action walk right.

**Expected behavior**
A profile job is started for the selected method / class etc.

**Screenshots**
N/A

**Environment :**
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Licensed to Oracle

Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8196M
Cores: 8
Non-Bundled Plugins:
    mobi.hsz.idea.gitignore (4.3.0)
    Karma (213.5744.122)
    org.dpytel.intellij.plugin.maventest (0.0.21)
    MavenRunHelper (4.18.212.000.3)

Kotlin: 213-1.5.10-release-949-IJ5744.223

**Additional context**
N/A

**Comment by kingsfleet** [comment]
Sorry for for the plain Java file IDEA offers:

Profile ‘xxxx()’ with ‘Async Profiler’

And similar under the “More Run/Debug options”

**Comment by krasa** [comment]
And does it work with Maven? My IntelliJ tells me `Error running 'server [jetty:run]': Can't profile provided goals`
