### ISSUE TITLE
Metaversion values are not interpreted

### ISSUE THREAD

**Issue by midorlo** [krasa/MavenHelper#90]
**Describe the bug**
Maven provides two (deprecated) special metaversion values LATEST and RELEASE. 

* LATEST equals the newest version.
* RELEASE equals the newest non-SNAPSHOT version.

MavenHelper ignores these values and suggests a version update on related dependencies.

**Screenshots**
![See](https://i.imgur.com/SoFeIr9.png)

**Comment by krasa** [comment]
that is IntelliJ feature or some other plugin

**Comment by midorlo** [comment]
Sorry then, i mixed this up. MavenHelper is the only related plugin that's active, so it's probably about ij itself
